language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - wget -qO- https://raw.githubusercontent.com/rubicks/autotoolme/master/autotoolme.sh | sh

script:
  - mkdir -vp _build
  - cd _build
  - autoreconf -ivf ..
  - ../configure
  - make clean all check distcheck install
