language: c

sudo: required

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - apt-get update

install:
  - apt-get install build-essential
  - wget -qO- https://raw.githubusercontent.com/rubicks/autotoolme/master/autotoolme.sh | sudo sh

script:
  - mkdir -vp _build
  - cd _build
  - autoreconf -ivf ..
  - ../configure
  - make clean all check distcheck install
